// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alexroden/checkout-kata-go/pkg/dynamodb"
	"github.com/alexroden/checkout-kata-go/pkg/repositories"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type MockRepository
func (_mock *MockRepository) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockRepository_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockRepository_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Context() *MockRepository_Context_Call {
	return &MockRepository_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockRepository_Context_Call) Run(run func()) *MockRepository_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Context_Call) Return(context1 context.Context) *MockRepository_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockRepository_Context_Call) RunAndReturn(run func() context.Context) *MockRepository_Context_Call {
	_c.Call.Return(run)
	return _c
}

// PutBasket provides a mock function for the type MockRepository
func (_mock *MockRepository) PutBasket(row *dynamodb.BasketRow) error {
	ret := _mock.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for PutBasket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*dynamodb.BasketRow) error); ok {
		r0 = returnFunc(row)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_PutBasket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutBasket'
type MockRepository_PutBasket_Call struct {
	*mock.Call
}

// PutBasket is a helper method to define mock.On call
//   - row *dynamodb.BasketRow
func (_e *MockRepository_Expecter) PutBasket(row any) *MockRepository_PutBasket_Call {
	return &MockRepository_PutBasket_Call{Call: _e.mock.On("PutBasket", row)}
}

func (_c *MockRepository_PutBasket_Call) Run(run func(row *dynamodb.BasketRow)) *MockRepository_PutBasket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dynamodb.BasketRow
		if args[0] != nil {
			arg0 = args[0].(*dynamodb.BasketRow)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_PutBasket_Call) Return(err error) *MockRepository_PutBasket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_PutBasket_Call) RunAndReturn(run func(row *dynamodb.BasketRow) error) *MockRepository_PutBasket_Call {
	_c.Call.Return(run)
	return _c
}

// PutBasketItem provides a mock function for the type MockRepository
func (_mock *MockRepository) PutBasketItem(row *dynamodb.BasketItemRow) error {
	ret := _mock.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for PutBasketItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*dynamodb.BasketItemRow) error); ok {
		r0 = returnFunc(row)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_PutBasketItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutBasketItem'
type MockRepository_PutBasketItem_Call struct {
	*mock.Call
}

// PutBasketItem is a helper method to define mock.On call
//   - row *dynamodb.BasketItemRow
func (_e *MockRepository_Expecter) PutBasketItem(row any) *MockRepository_PutBasketItem_Call {
	return &MockRepository_PutBasketItem_Call{Call: _e.mock.On("PutBasketItem", row)}
}

func (_c *MockRepository_PutBasketItem_Call) Run(run func(row *dynamodb.BasketItemRow)) *MockRepository_PutBasketItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dynamodb.BasketItemRow
		if args[0] != nil {
			arg0 = args[0].(*dynamodb.BasketItemRow)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_PutBasketItem_Call) Return(err error) *MockRepository_PutBasketItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_PutBasketItem_Call) RunAndReturn(run func(row *dynamodb.BasketItemRow) error) *MockRepository_PutBasketItem_Call {
	_c.Call.Return(run)
	return _c
}

// SetDb provides a mock function for the type MockRepository
func (_mock *MockRepository) SetDb(db repositories.DynamoDBAPI) {
	_mock.Called(db)
	return
}

// MockRepository_SetDb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDb'
type MockRepository_SetDb_Call struct {
	*mock.Call
}

// SetDb is a helper method to define mock.On call
//   - db repositories.DynamoDBAPI
func (_e *MockRepository_Expecter) SetDb(db any) *MockRepository_SetDb_Call {
	return &MockRepository_SetDb_Call{Call: _e.mock.On("SetDb", db)}
}

func (_c *MockRepository_SetDb_Call) Run(run func(db repositories.DynamoDBAPI)) *MockRepository_SetDb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 repositories.DynamoDBAPI
		if args[0] != nil {
			arg0 = args[0].(repositories.DynamoDBAPI)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_SetDb_Call) Return() *MockRepository_SetDb_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_SetDb_Call) RunAndReturn(run func(db repositories.DynamoDBAPI)) *MockRepository_SetDb_Call {
	_c.Run(run)
	return _c
}
