formatter: goimports
log-level: info
template: testify
all: false
recursive: true

packages:
  github.com/alexroden/checkout-kata-go/internal/dynamo-init:
    config:
      all: true
      dir: internal/mocks/dynamo-init
      pkgname: mocks
      structname: '{{.Mock}}{{.InterfaceName}}'
      filename: '{{.InterfaceName}}_mock.go'
      recursive: true
      force-file-write: true