# syntax=docker/dockerfile:1.4

FROM golang:1.26.4-alpine

WORKDIR /api

RUN apk add --no-cache

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

COPY . .

WORKDIR /api

RUN go build -o main ./cmd

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
