# syntax=docker/dockerfile:1.4

FROM golang:1.26.4-alpine

WORKDIR /api

RUN apk add --no-cache \
    git \
    curl \
    wget

COPY go.mod go.sum ./

COPY . .

CMD ["go", "run", "./internal/dynamo-init"]
