// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Errors provides a mock function for the type MockRepository
func (_mock *MockRepository) Errors(n int) error {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Errors")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Errors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errors'
type MockRepository_Errors_Call struct {
	*mock.Call
}

// Errors is a helper method to define mock.On call
//   - n int
func (_e *MockRepository_Expecter) Errors(n any) *MockRepository_Errors_Call {
	return &MockRepository_Errors_Call{Call: _e.mock.On("Errors", n)}
}

func (_c *MockRepository_Errors_Call) Run(run func(n int)) *MockRepository_Errors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Errors_Call) Return(err error) *MockRepository_Errors_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Errors_Call) RunAndReturn(run func(n int) error) *MockRepository_Errors_Call {
	_c.Call.Return(run)
	return _c
}

// HasError provides a mock function for the type MockRepository
func (_mock *MockRepository) HasError() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasError")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRepository_HasError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasError'
type MockRepository_HasError_Call struct {
	*mock.Call
}

// HasError is a helper method to define mock.On call
func (_e *MockRepository_Expecter) HasError() *MockRepository_HasError_Call {
	return &MockRepository_HasError_Call{Call: _e.mock.On("HasError")}
}

func (_c *MockRepository_HasError_Call) Run(run func()) *MockRepository_HasError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_HasError_Call) Return(b bool) *MockRepository_HasError_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRepository_HasError_Call) RunAndReturn(run func() bool) *MockRepository_HasError_Call {
	_c.Call.Return(run)
	return _c
}

// ScanItem provides a mock function for the type MockRepository
func (_mock *MockRepository) ScanItem(sku string) {
	_mock.Called(sku)
	return
}

// MockRepository_ScanItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanItem'
type MockRepository_ScanItem_Call struct {
	*mock.Call
}

// ScanItem is a helper method to define mock.On call
//   - sku string
func (_e *MockRepository_Expecter) ScanItem(sku any) *MockRepository_ScanItem_Call {
	return &MockRepository_ScanItem_Call{Call: _e.mock.On("ScanItem", sku)}
}

func (_c *MockRepository_ScanItem_Call) Run(run func(sku string)) *MockRepository_ScanItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ScanItem_Call) Return() *MockRepository_ScanItem_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_ScanItem_Call) RunAndReturn(run func(sku string)) *MockRepository_ScanItem_Call {
	_c.Run(run)
	return _c
}

// Session provides a mock function for the type MockRepository
func (_mock *MockRepository) Session() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Session")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRepository_Session_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Session'
type MockRepository_Session_Call struct {
	*mock.Call
}

// Session is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Session() *MockRepository_Session_Call {
	return &MockRepository_Session_Call{Call: _e.mock.On("Session")}
}

func (_c *MockRepository_Session_Call) Run(run func()) *MockRepository_Session_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Session_Call) Return(s string) *MockRepository_Session_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRepository_Session_Call) RunAndReturn(run func() string) *MockRepository_Session_Call {
	_c.Call.Return(run)
	return _c
}

// SetSession provides a mock function for the type MockRepository
func (_mock *MockRepository) SetSession(session string) {
	_mock.Called(session)
	return
}

// MockRepository_SetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSession'
type MockRepository_SetSession_Call struct {
	*mock.Call
}

// SetSession is a helper method to define mock.On call
//   - session string
func (_e *MockRepository_Expecter) SetSession(session any) *MockRepository_SetSession_Call {
	return &MockRepository_SetSession_Call{Call: _e.mock.On("SetSession", session)}
}

func (_c *MockRepository_SetSession_Call) Run(run func(session string)) *MockRepository_SetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_SetSession_Call) Return() *MockRepository_SetSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_SetSession_Call) RunAndReturn(run func(session string)) *MockRepository_SetSession_Call {
	_c.Run(run)
	return _c
}

// StartSession provides a mock function for the type MockRepository
func (_mock *MockRepository) StartSession() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type MockRepository_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
func (_e *MockRepository_Expecter) StartSession() *MockRepository_StartSession_Call {
	return &MockRepository_StartSession_Call{Call: _e.mock.On("StartSession")}
}

func (_c *MockRepository_StartSession_Call) Run(run func()) *MockRepository_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_StartSession_Call) Return(s string, err error) *MockRepository_StartSession_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_StartSession_Call) RunAndReturn(run func() (string, error)) *MockRepository_StartSession_Call {
	_c.Call.Return(run)
	return _c
}
