// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionManager creates a new instance of MockSessionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionManager {
	mock := &MockSessionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionManager is an autogenerated mock type for the SessionManager type
type MockSessionManager struct {
	mock.Mock
}

type MockSessionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionManager) EXPECT() *MockSessionManager_Expecter {
	return &MockSessionManager_Expecter{mock: &_m.Mock}
}

// Session provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) Session() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Session")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSessionManager_Session_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Session'
type MockSessionManager_Session_Call struct {
	*mock.Call
}

// Session is a helper method to define mock.On call
func (_e *MockSessionManager_Expecter) Session() *MockSessionManager_Session_Call {
	return &MockSessionManager_Session_Call{Call: _e.mock.On("Session")}
}

func (_c *MockSessionManager_Session_Call) Run(run func()) *MockSessionManager_Session_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionManager_Session_Call) Return(s string) *MockSessionManager_Session_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSessionManager_Session_Call) RunAndReturn(run func() string) *MockSessionManager_Session_Call {
	_c.Call.Return(run)
	return _c
}

// SetSession provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) SetSession(session string) {
	_mock.Called(session)
	return
}

// MockSessionManager_SetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSession'
type MockSessionManager_SetSession_Call struct {
	*mock.Call
}

// SetSession is a helper method to define mock.On call
//   - session string
func (_e *MockSessionManager_Expecter) SetSession(session any) *MockSessionManager_SetSession_Call {
	return &MockSessionManager_SetSession_Call{Call: _e.mock.On("SetSession", session)}
}

func (_c *MockSessionManager_SetSession_Call) Run(run func(session string)) *MockSessionManager_SetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionManager_SetSession_Call) Return() *MockSessionManager_SetSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionManager_SetSession_Call) RunAndReturn(run func(session string)) *MockSessionManager_SetSession_Call {
	_c.Run(run)
	return _c
}

// StartSession provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) StartSession() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionManager_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type MockSessionManager_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
func (_e *MockSessionManager_Expecter) StartSession() *MockSessionManager_StartSession_Call {
	return &MockSessionManager_StartSession_Call{Call: _e.mock.On("StartSession")}
}

func (_c *MockSessionManager_StartSession_Call) Run(run func()) *MockSessionManager_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionManager_StartSession_Call) Return(s string, err error) *MockSessionManager_StartSession_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSessionManager_StartSession_Call) RunAndReturn(run func() (string, error)) *MockSessionManager_StartSession_Call {
	_c.Call.Return(run)
	return _c
}
