// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Errors provides a mock function for the type MockValidator
func (_mock *MockValidator) Errors(n int) error {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Errors")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_Errors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errors'
type MockValidator_Errors_Call struct {
	*mock.Call
}

// Errors is a helper method to define mock.On call
//   - n int
func (_e *MockValidator_Expecter) Errors(n any) *MockValidator_Errors_Call {
	return &MockValidator_Errors_Call{Call: _e.mock.On("Errors", n)}
}

func (_c *MockValidator_Errors_Call) Run(run func(n int)) *MockValidator_Errors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValidator_Errors_Call) Return(err error) *MockValidator_Errors_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_Errors_Call) RunAndReturn(run func(n int) error) *MockValidator_Errors_Call {
	_c.Call.Return(run)
	return _c
}

// HasError provides a mock function for the type MockValidator
func (_mock *MockValidator) HasError() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasError")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockValidator_HasError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasError'
type MockValidator_HasError_Call struct {
	*mock.Call
}

// HasError is a helper method to define mock.On call
func (_e *MockValidator_Expecter) HasError() *MockValidator_HasError_Call {
	return &MockValidator_HasError_Call{Call: _e.mock.On("HasError")}
}

func (_c *MockValidator_HasError_Call) Run(run func()) *MockValidator_HasError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidator_HasError_Call) Return(b bool) *MockValidator_HasError_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockValidator_HasError_Call) RunAndReturn(run func() bool) *MockValidator_HasError_Call {
	_c.Call.Return(run)
	return _c
}
