// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDynamoDBAPI creates a new instance of MockDynamoDBAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDynamoDBAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDynamoDBAPI {
	mock := &MockDynamoDBAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDynamoDBAPI is an autogenerated mock type for the DynamoDBAPI type
type MockDynamoDBAPI struct {
	mock.Mock
}

type MockDynamoDBAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDynamoDBAPI) EXPECT() *MockDynamoDBAPI_Expecter {
	return &MockDynamoDBAPI_Expecter{mock: &_m.Mock}
}

// BatchWriteItem provides a mock function for the type MockDynamoDBAPI
func (_mock *MockDynamoDBAPI) BatchWriteItem(ctx context.Context, params *dynamodb.BatchWriteItemInput, optFns ...func(*dynamodb.Options)) (*dynamodb.BatchWriteItemOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BatchWriteItem")
	}

	var r0 *dynamodb.BatchWriteItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.BatchWriteItemInput, ...func(*dynamodb.Options)) (*dynamodb.BatchWriteItemOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.BatchWriteItemInput, ...func(*dynamodb.Options)) *dynamodb.BatchWriteItemOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.BatchWriteItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.BatchWriteItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDynamoDBAPI_BatchWriteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchWriteItem'
type MockDynamoDBAPI_BatchWriteItem_Call struct {
	*mock.Call
}

// BatchWriteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - params *dynamodb.BatchWriteItemInput
//   - optFns ...func(*dynamodb.Options)
func (_e *MockDynamoDBAPI_Expecter) BatchWriteItem(ctx any, params any, optFns ...any) *MockDynamoDBAPI_BatchWriteItem_Call {
	return &MockDynamoDBAPI_BatchWriteItem_Call{Call: _e.mock.On("BatchWriteItem",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *MockDynamoDBAPI_BatchWriteItem_Call) Run(run func(ctx context.Context, params *dynamodb.BatchWriteItemInput, optFns ...func(*dynamodb.Options))) *MockDynamoDBAPI_BatchWriteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.BatchWriteItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.BatchWriteItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDynamoDBAPI_BatchWriteItem_Call) Return(batchWriteItemOutput *dynamodb.BatchWriteItemOutput, err error) *MockDynamoDBAPI_BatchWriteItem_Call {
	_c.Call.Return(batchWriteItemOutput, err)
	return _c
}

func (_c *MockDynamoDBAPI_BatchWriteItem_Call) RunAndReturn(run func(ctx context.Context, params *dynamodb.BatchWriteItemInput, optFns ...func(*dynamodb.Options)) (*dynamodb.BatchWriteItemOutput, error)) *MockDynamoDBAPI_BatchWriteItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTable provides a mock function for the type MockDynamoDBAPI
func (_mock *MockDynamoDBAPI) CreateTable(ctx context.Context, input *dynamodb.CreateTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.CreateTableOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateTable")
	}

	var r0 *dynamodb.CreateTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.CreateTableInput, ...func(*dynamodb.Options)) (*dynamodb.CreateTableOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.CreateTableInput, ...func(*dynamodb.Options)) *dynamodb.CreateTableOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.CreateTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.CreateTableInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDynamoDBAPI_CreateTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTable'
type MockDynamoDBAPI_CreateTable_Call struct {
	*mock.Call
}

// CreateTable is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.CreateTableInput
//   - opts ...func(*dynamodb.Options)
func (_e *MockDynamoDBAPI_Expecter) CreateTable(ctx any, input any, opts ...any) *MockDynamoDBAPI_CreateTable_Call {
	return &MockDynamoDBAPI_CreateTable_Call{Call: _e.mock.On("CreateTable",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *MockDynamoDBAPI_CreateTable_Call) Run(run func(ctx context.Context, input *dynamodb.CreateTableInput, opts ...func(*dynamodb.Options))) *MockDynamoDBAPI_CreateTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.CreateTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.CreateTableInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDynamoDBAPI_CreateTable_Call) Return(createTableOutput *dynamodb.CreateTableOutput, err error) *MockDynamoDBAPI_CreateTable_Call {
	_c.Call.Return(createTableOutput, err)
	return _c
}

func (_c *MockDynamoDBAPI_CreateTable_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.CreateTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.CreateTableOutput, error)) *MockDynamoDBAPI_CreateTable_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeTable provides a mock function for the type MockDynamoDBAPI
func (_mock *MockDynamoDBAPI) DescribeTable(ctx context.Context, input *dynamodb.DescribeTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.DescribeTableOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeTable")
	}

	var r0 *dynamodb.DescribeTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTableInput, ...func(*dynamodb.Options)) (*dynamodb.DescribeTableOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTableInput, ...func(*dynamodb.Options)) *dynamodb.DescribeTableOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DescribeTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DescribeTableInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDynamoDBAPI_DescribeTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeTable'
type MockDynamoDBAPI_DescribeTable_Call struct {
	*mock.Call
}

// DescribeTable is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.DescribeTableInput
//   - opts ...func(*dynamodb.Options)
func (_e *MockDynamoDBAPI_Expecter) DescribeTable(ctx any, input any, opts ...any) *MockDynamoDBAPI_DescribeTable_Call {
	return &MockDynamoDBAPI_DescribeTable_Call{Call: _e.mock.On("DescribeTable",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *MockDynamoDBAPI_DescribeTable_Call) Run(run func(ctx context.Context, input *dynamodb.DescribeTableInput, opts ...func(*dynamodb.Options))) *MockDynamoDBAPI_DescribeTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DescribeTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DescribeTableInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDynamoDBAPI_DescribeTable_Call) Return(describeTableOutput *dynamodb.DescribeTableOutput, err error) *MockDynamoDBAPI_DescribeTable_Call {
	_c.Call.Return(describeTableOutput, err)
	return _c
}

func (_c *MockDynamoDBAPI_DescribeTable_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.DescribeTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.DescribeTableOutput, error)) *MockDynamoDBAPI_DescribeTable_Call {
	_c.Call.Return(run)
	return _c
}
